//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypożyczający
    {
        public int Id { get; set; }
        public string Imię { get; set; }
        public string Nazwisko { get; set; }
        public int Wypożyczone_książki { get; set; }
        public string Telefon_kontaktowy { get; set; }
        public string Adres_mailowy { get; set; }
    
        public virtual Wyp__Książki Wyp__Książki { get; set; }
    }
}
