//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UczniowieSzkolyEntities : DbContext
    {
        public UczniowieSzkolyEntities()
            : base("name=UczniowieSzkolyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Wyp__Książki> Wyp__Książki { get; set; }
        public virtual DbSet<Wypożyczający> Wypożyczający { get; set; }
    }
}
