//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class Wypożyczający
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Podaj imię")]
        [Display(Name = "Imię")]
        [MaxLength(20)]
        [MinLength(2)]
        public string Imię { get; set; }
        [Required(ErrorMessage = "Podaj nazwisko")]
        [Display(Name = "Nazwisko")]
        [MaxLength(20)]
        [MinLength(2)]
        public string Nazwisko { get; set; }
        [Required(ErrorMessage = "Wybierz książkę")]
        [Display(Name = "Tytuł książki")]
        public int TytułKsiążkiId { get; set; }
        [Required(ErrorMessage = "Podaj numer telefonu")]
        [Display(Name = "Numer telefonu")]
        [Phone(ErrorMessage = "Podaj właściwy format dla numeru telefonu")]
        [MaxLength(25)]
        [MinLength(9)]
        public string NumerTelefonu { get; set; }
        [Required(ErrorMessage = "Podaj adres e-mail")]
        [Display(Name = "Adres e-mail")]
        [EmailAddress(ErrorMessage = "Podaj właściwy format dla adresu e-mail")]
        [MaxLength(50)]
        [MinLength(6)]
        public string AdresMailowy { get; set; }
    
        public virtual Książki Książki { get; set; }
    }
}
